source 'https://rubygems.org'
ruby '2.0.0'

gem 'rails','4.0.0'

group :development do
  gem 'sqlite3','1.3.7'
end
group :production do
  gem 'pg','0.15.1'
end
gem 'sass-rails','~> 4.0.0'
gem 'uglifier','>= 1.3.0'
gem 'coffee-rails','~> 4.0.0'
gem 'jquery-rails','2.2.1'
gem 'turbolinks','1.1.1'
gem 'jbuilder', '~> 1.0.2'

group :doc do
  gem 'sdoc','0.3.20', require: false
end

